print('  Entrevista de Emprego Rafel')
nome = input('Qual o seu nome? ')
idade = input('Qual a sua idade? ')
civil = input(' Solteiro ou Casado?')
prof = input(' Qual foi sua ultima profissao? ')
tempo = input('Trabalhou quanto tempo na ultima empresa? ')
sala = input(' Qual foi seu ultimo salario? ')
sal2 = input(' Quanto voce pretende ganhar em nossa empresa? ')
filh = input(' Voce tem filhos? Qual as idades? ')
ond = input(' Como conheceu nossa empresa? ')
dispo = input(' Tem disponibilidade de horario? ')
ctt = input(' Deixe seu numero para contato')
print(' Obrigado por entrar em contato com nossa empresa {}, em breve entraremos em contato, Tenha uma boa sorte'.format(nome))
print(' Dados do candidato',( nome, idade, civil, prof, tempo, sala, sal2, filh, ond, dispo, ctt))
# print(' Dados do candidato'(nome, idade))

